spring.application.name=eeveevoiding-responsibilities-campus-events


spring.security.user.name=${SPRING_SECURITY_USER_NAME:admin}
spring.security.user.password=${SPRING_SECURITY_USER_PASSWORD:admin}

springdoc.swagger-ui.path=/swagger-ui.html
